[cursor]
style = "Block"

[colors]
draw_bold_text_with_bright_colors = false

# Dracula ----------------------
[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"
bright_foreground = "#ffffff"

[colors.normal]
black = "#21222c"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"

[colors.bright]
black = "#6272a4"
red = "#ff6e6e"
green = "#69ff94"
yellow = "#ffffa5"
blue = "#d6acff"
magenta = "#ff92df"
cyan = "#a4ffff"
white = "#ffffff"
# ----------------------

# Tokyonight ---------------------
# [colors.primary]
# background = '#20222b'
# foreground = '#a9b1d6'
#
# [colors.normal]
# black =   '#32344a'
# red=     '#f7768e'
# green=   '#9ece6a'
# yellow=  '#e0af68'
# blue=    '#7aa2f7'
# magenta= '#ad8ee6'
# cyan=    '#449dab'
# white=   '#787c99'
#
# [colors.bright]
# black = '#444b6a'
# red = '#ff7a93'
# green = '#b9f27c'
# yellow = '#ff9e64'
# blue = '#7da6ff'
# magenta = '#bb9af7'
# cyan = '#0db9d7'
# white = '#acb0d0'
# ---------------------

[colors.cursor]
text = "#282a36"
cursor = "#f8f8f2"

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.selection]
text = "CellForeground"
background = "#44475a"

[colors.search.matches]
foreground = "#44475a"
background = "#50fa7b"

[colors.search.focused_match]
foreground = "#44475a"
background = "#ffb86c"

[colors.footer_bar]
background = "#282a36"
foreground = "#f8f8f2"

[colors.hints.start]
foreground = "#282a36"
background = "#f1fa8c"

[colors.hints.end]
foreground = "#f1fa8c"
background = "#282a36"

[env]
TERM = "xterm-256color"

[font]
size = 11.25

[font.normal]
# family = "Hack Nerd Font"
family = "JetBrainsMono Nerd Font"
style = "Light"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[scrolling]
history = 5000
multiplier = 3

[window]
dynamic_padding = true
opacity = 1
blur = false
decorations = "Full"
title = "Alacritty"
startup_mode = "Windowed"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10

[keyboard]
bindings = [
    { key= "F",        mods= "Control|Shift", mode= "~Search",     action= "ReceiveChar" },
    { key= "F",        mods= "Command",       mode= "~Search",     action= "ReceiveChar" },
    { key= "B",        mods= "Control|Shift", mode= "~Search",     action= "ReceiveChar" },
    { key= "B",        mods= "Command",       mode= "~Search",     action= "ReceiveChar" },

    { key= "L",        mods= "Control",       mode= "~Vi|~Search",     action= "ReceiveChar" },

    { key= "PageUp",   mods= "shift",         mode= "~Alt",     action= "ReceiveChar" },
    { key= "PageDown", mods= "shift",         mode= "~Alt",     action= "ReceiveChar" },
    { key= "Home",     mods= "shift",         mode= "~Alt",     action= "ReceiveChar" },
    { key= "End",      mods= "shift",         mode= "~Alt",     action= "ReceiveChar" },

    { key= "Space",    mods= "Control|Shift", mode= "~Search",     action= "ReceiveChar" },
    { key= "I",                               mode= "Vi|~Search",  action= "ReceiveChar" },
    { key= "C",        mods= "Control",       mode= "Vi|~Search",  action= "ReceiveChar" },
    { key= "Back",     mods= "Control",                             chars= "\u0017" }
]
